version: "3"
services:

  el-client:
    hostname: el-client
    container_name: el-client
    image: nethermind/nethermind:latest
    restart: always
    stop_grace_period: 1m
    command: |
      --datadir=/data
    networks:
      gnosis_net:
        ipv4_address: 192.168.32.100
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    volumes:
      - /home/$USER/gnosis/el-client:/data
      - /home/$USER/gnosis/jwtsecret/jwtsecret:/jwtsecret
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - NETHERMIND_CONFIG=xdai_archive
      - NETHERMIND_JSONRPCCONFIG_ENABLED=true
      - NETHERMIND_JSONRPCCONFIG_HOST=192.168.32.100
      - NETHERMIND_JSONRPCCONFIG_PORT=8545
      - NETHERMIND_JSONRPCCONFIG_JWTSECRETFILE=/jwtsecret
      - NETHERMIND_JSONRPCCONFIG_ENGINEHOST=192.168.32.100
      - NETHERMIND_JSONRPCCONFIG_ENGINEPORT=8551
      - NETHERMIND_MERGECONFIG_ENABLED=true
    logging:
      driver: "local"

  cl-node:
    hostname: cl-node
    container_name: cl-node
    image: sigp/lighthouse:latest-modern
    restart: always
    depends_on:
      - el-client
    command: |
      lighthouse beacon_node
      --network gnosis
      --discovery-port 12000
      --port 13000
      --execution-endpoint http://192.168.32.100:8551
      --execution-jwt /jwtsecret
      --datadir /data
      --http
      --http-address 192.168.32.101
      --enr-address $WAN_IP
      --enr-udp-port 12000
      --target-peers 80
      --debug-level info
      --suggested-fee-recipient $FEE_RECIPIENT
    networks:
      gnosis_net:
        ipv4_address: 192.168.32.101
    ports:
      - "12000:12000/udp" #p2p
      - "13000:13000/tcp" #p2p
    volumes:
      - /home/$USER/gnosis/cl-client/data:/data
      - /home/$USER/gnosis/jwtsecret/jwtsecret:/jwtsecret
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "local"

  cl-validator:
    hostname: cl-validator
    container_name: cl-validator
    image: sigp/lighthouse:latest-modern
    restart: always
    depends_on:
      - cl-node
    command: |
      lighthouse validator_client
      --network gnosis
      --enable-doppelganger-protection
      --validators-dir /data/validators
      --beacon-nodes http://192.168.32.101:5052
      --suggested-fee-recipient $FEE_RECIPIENT
      --graffiti $GRAFFITI
    networks:
      gnosis_net:
        ipv4_address: 192.168.32.102
    volumes:
      - /home/$USER/gnosis/cl-client/validators:/data/validators
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "local"

networks:
  gnosis_net:
    ipam:
      driver: default
      config:
        - subnet: 192.168.32.0/24
